### ISSUE TITLE
The "install via ipfs-desktop" release 💾✨ 

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/npm-on-ipfs#106]
We're gonna bundle `ipfs-npm` with IPFS Desktop, as an experiement that user can toggle.

_this list may change, but this is what we know we need to do so far_

### TODO

- [x] Don't invoke IPFS for local commands like `npm ls` https://github.com/ipfs-shipyard/npm-on-ipfs/issues/95
- [ ] Get the keys to the registry mirror infrastructure
- [ ] Ensure sufficient monitoring of the mirror is in place
- [x] Install `ipfs-npm` from IPFS Desktop https://github.com/ipfs-shipyard/ipfs-desktop/pull/911
- [x] Update Web UI with toggle for IPFS dekstop https://github.com/ipfs-shipyard/ipfs-desktop/issues/907

### Nice to have
- [ ] Do invoke IPFS for `npx`  https://github.com/ipfs-shipyard/npm-on-ipfs/issues/96
- [ ] Quiter installs AKA: what should the CLI say https://github.com/ipfs-shipyard/npm-on-ipfs/issues/104
- [ ] Discover and use existing ipfs api where available https://github.com/ipfs-shipyard/npm-on-ipfs/issues/105

**Comment by daviddias** [comment]
This does sound very exciting!

**Comment by momack2** [comment]
@hacdias I saw npm-on-ipfs is listed for 0.9.0 - does that mean this issue is complete?

**Comment by hacdias** [comment]
@momack2 thanks for the heads up. All of the problems left to solve have their own issues so they can be tackled separately.
